# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'nutring' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for nutring
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'

  target 'nutringTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
