# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'nutring' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!

  # Pods for nutring
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  pod 'React', :path => '../node_modules/react-native'
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      if target.name == "React"
        target.remove_from_project
      end
    end
  end

  target 'nutring-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'

  end

end
